# Generated by Django 3.0.3 on 2020-03-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_delete_profile'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major1', to='master.Specialization', verbose_name='Vertiefungsfach 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major2', to='master.Specialization', verbose_name='Vertiefungsfach 2'),
        ),
    ]
