# Generated by Django 3.0.3 on 2020-02-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('type_abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=100)),
                ('specialization_abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='Titel')),
                ('credit_points', models.IntegerField(default=0, verbose_name='ECTS')),
                ('course_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.CourseType', verbose_name='Kurstyp')),
                ('specializations', models.ManyToManyField(blank=True, to='master.Specialization', verbose_name='Vertiefungsfächer laut Modulhandbuch')),
            ],
        ),
    ]
