# Generated by Django 3.0.3 on 2020-02-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Studienteil')),
            ],
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='type_abbreviation',
            field=models.CharField(max_length=5, verbose_name='Abkürzung'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='type_name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_abbreviation',
            field=models.CharField(max_length=10, verbose_name='Abkürzung'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
