# Generated by Django 3.0.5 on 2020-05-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Semester', verbose_name='Prüfungssemester'),
        ),
    ]
