# Generated by Django 3.0.5 on 2020-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20200502_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='ECTS'),
        ),
    ]
