# Generated by Django 3.0.5 on 2020-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20200502_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prüfungstermin'),
        ),
    ]
