# Generated by Django 3.0.3 on 2020-03-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_ects_creditable',
            field=models.IntegerField(null=True, verbose_name='Maximale Anzahl anrechenbarer ECTS'),
        ),
        migrations.AddField(
            model_name='category',
            name='min_ects_required',
            field=models.IntegerField(null=True, verbose_name='Minimal nötige Anzahl ECTS in diesem Bereich'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='max_ects_creditable',
            field=models.IntegerField(null=True, verbose_name='Maximale Anzahl anrechenbarer ECTS'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='min_ects_required',
            field=models.IntegerField(null=True, verbose_name='Minimal nötige Anzahl ECTS in dieser Kategorie'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Studienteil'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='type_abbreviation',
            field=models.CharField(max_length=5, unique=True, verbose_name='Abkürzung'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='type_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_abbreviation',
            field=models.CharField(max_length=10, unique=True, verbose_name='Abkürzung'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
