# Generated by Django 3.0.3 on 2020-03-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20200301_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='max_ects_creditable',
            field=models.IntegerField(blank=True, verbose_name='Maximale Anzahl anrechenbarer ECTS'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='min_ects_required',
            field=models.IntegerField(blank=True, verbose_name='Minimal nötige Anzahl ECTS in dieser Kategorie'),
        ),
    ]
