# Generated by Django 3.0.3 on 2020-03-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20200301_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('SS', 'Sommersemester'), ('WS', 'Wintersemester')], max_length=2)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Semester', verbose_name='Prüfungssemester'),
        ),
    ]
