# Generated by Django 3.0.3 on 2020-03-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20200301_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Note'),
        ),
    ]
