# Generated by Django 3.0.3 on 2020-03-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='included',
            field=models.BooleanField(default=True, verbose_name='In Berechnung mit einbeziehen?'),
        ),
    ]
