# Generated by Django 3.0.3 on 2020-03-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_course_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Note'),
        ),
    ]
