# Generated by Django 3.0.3 on 2020-03-03 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0012_auto_20200301_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='included',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Note')),
                ('included', models.BooleanField(default=True, verbose_name='In Berechnung mit einbeziehen?')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Category', verbose_name='Kategorie')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Course', verbose_name='Kurs')),
                ('semester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Semester', verbose_name='Prüfungssemester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
