# Generated by Django 3.0.3 on 2020-03-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
